// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEKxLOnrRMNMtusEYiPFj32HD2tR7WBhw',
    appId: '1:930238557912:web:4ebfea5079543c471e71ad',
    messagingSenderId: '930238557912',
    projectId: 'aquora-795ac',
    authDomain: 'aquora-795ac.firebaseapp.com',
    storageBucket: 'aquora-795ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3jDOSQKoHz8lA5QERCNA7xFVw-vvCaBY',
    appId: '1:930238557912:android:25d8191ede110a441e71ad',
    messagingSenderId: '930238557912',
    projectId: 'aquora-795ac',
    storageBucket: 'aquora-795ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYUQ8ySnKAONXBNVzUKXi98QRwNEG_Uk',
    appId: '1:930238557912:ios:7be12f259463a87c1e71ad',
    messagingSenderId: '930238557912',
    projectId: 'aquora-795ac',
    storageBucket: 'aquora-795ac.firebasestorage.app',
    iosBundleId: 'com.example.aquoraDashboardV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWYUQ8ySnKAONXBNVzUKXi98QRwNEG_Uk',
    appId: '1:930238557912:ios:7be12f259463a87c1e71ad',
    messagingSenderId: '930238557912',
    projectId: 'aquora-795ac',
    storageBucket: 'aquora-795ac.firebasestorage.app',
    iosBundleId: 'com.example.aquoraDashboardV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEKxLOnrRMNMtusEYiPFj32HD2tR7WBhw',
    appId: '1:930238557912:web:8159feb9d656c1661e71ad',
    messagingSenderId: '930238557912',
    projectId: 'aquora-795ac',
    authDomain: 'aquora-795ac.firebaseapp.com',
    storageBucket: 'aquora-795ac.firebasestorage.app',
  );
}
